apiVersion: v1
kind: Namespace
metadata:
  name: httpd
  labels:
    name: httpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: httpd
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: httpd
  labels:
    app: httpd
spec:
  ports:
  - port: 80
  selector:
    app: httpd